apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: backend-golden-path # TODO: Change this name to your application name
  namespace: appsec # TODO: Change this to your team's namespace
spec:
  ingresses:
    - https://backend-golden-path.intern.dev.nav.no # TODO: Change this to your desired ingress
  image: {{image}}
  port: 8080
  replicas:
    max: 1
    min: 1
  resources:
    requests:
      cpu: 50m
      memory: 32Mi
  observability:
    logging:
      destinations:
        - id: loki