apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tpt-data-collector
  namespace: appsec
spec:
  image: {{image}}
  port: 8080
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: tpt-backend
    outbound:
      external:
        - host: github.com
  liveness:
    path: /internal/isAlive
  readiness:
    path: /internal/isAlive
  replicas:
    max: 1
    min: 1
  kafka:
    pool: nav-prod
  resources:
    requests:
      cpu: 20m
      memory: 256Mi
  observability:
    logging:
      destinations:
        - id: loki
  prometheus:
    enabled: true
    path: /metrics
  gcp:
    bigQueryDatasets:
      - name: appsec
        permission: READ
  env:
    - name: BIGQUERY_DATASET_ID
      value: appsec
    - name: TPT_TOPIC
      value: appsec.tpt
    - name: KAFKA_CLIENT_ID
      value: tpt-data-collector
  envFrom:
    - secret: tpt-data-collector
