apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tpt-data-collector
  namespace: appsec
spec:
  image: {{image}}
  port: 8080
  replicas:
    max: 1
    min: 1
  resources:
    requests:
      cpu: 50m
      memory: 32Mi
  observability:
    logging:
      destinations:
        - id: loki
  gcp:
    bigQueryDatasets:
      - name: appsec
        permission: READ