apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tpt-data-collector
  namespace: appsec
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /internal/isAlive
  readiness:
    path: /internal/isAlive
  replicas:
    max: 1
    min: 1
  kafka:
    pool: nav-prod
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
  observability:
    logging:
      destinations:
        - id: loki
  gcp:
    bigQueryDatasets:
      - name: appsec
        permission: READ
  env:
    - name: BIGQUERY_DATASET_ID
      value: appsec
    - name: TPT_TOPIC
      value: appsec.tpt
    - name: KAFKA_CLIENT_ID
      value: tpt-data-collector